// examples/weather/react-nano_kit/src/components/CityInput.tsx
import { useSignal } from '@nano_kit/react'
import {
  $locationSearchInputValue,
  $citySuggestions
} from '../stores/location.js'
import { Autocomplete } from './Autocomplete.jsx'

export function CityInput() {
  const locationSearchQuery = useSignal($locationSearchInputValue)
  const citySuggestions = useSignal($citySuggestions)

  return (
    <Autocomplete
      id='city'
      label='Search for a city'
      name='city'
      value={locationSearchQuery}
      suggestions={citySuggestions}
      onChange={$locationSearchInputValue}
    />
  )
}

// examples/weather/svelte-nano_kit/src/components/CityInput.svelte
<script lang="ts">
  import {
    $locationSearchInputValue as locationSearchInputValue,
    $citySuggestions as citySuggestions
  } from '../stores/location.js'
  import Autocomplete from './Autocomplete.svelte'
</script>

<Autocomplete
  id="city"
  label="Search for a city"
  name="city"
  value={$locationSearchInputValue}
  suggestions={$citySuggestions}
  onChange={(value) => $locationSearchInputValue = value}
/>
