// examples/rick-and-morty/svelte-nano_kit/src/App.svelte
<script lang="ts">
  import {
    getPageSignal,
    router
  } from '@nano_kit/svelte-router'
  import { $location as location } from './stores/router.js'
  import { pages } from './pages.js'

  const page = router(location, pages)
  const pageComponent = getPageSignal(page)
</script>

{#if $pageComponent}
  {@const Page = $pageComponent}
  <Page />
{/if}

// examples/cvapp/react-nano_kit/src/App.tsx
import { effect } from '@nano_kit/store'
import {
  page,
  layout,
  resetScroll,
  useNavigationListenLinks,
  router,
  usePageSignal
} from '@nano_kit/react-router'
import { useEffect } from 'react'
import {
  $location,
  navigation
} from './stores/router'
import { Layout } from './pages/Layout'
import { Home } from './pages/Home'
import { Application } from './pages/Application'

const $page = router($location, [
  layout(Layout, [
    page('home', Home),
    page('newApplication', Application),
    page('application', Application)
  ])
])

export function App() {
  const Page = usePageSignal($page)

  useNavigationListenLinks(navigation)

  useEffect(() => effect((initial) => {
    const shouldReset = $location.$action() !== 'replace' && !initial

    if (shouldReset) {
      resetScroll()
    }
  }), [])

  return Page && <Page/>
}
