// examples/weather/react-nano_kit-di/src/components/CityInput.tsx
import {
  useInject,
  useSignal
} from '@nano_kit/react'
import {
  LocationSearch$,
  CitySuggestions$
} from '../stores/location.js'
import { Autocomplete } from './Autocomplete.jsx'

export function CityInput() {
  const { $searchInputValue } = useInject(LocationSearch$)
  const { $suggestions } = useInject(CitySuggestions$)
  const searchQuery = useSignal($searchInputValue)
  const suggestions = useSignal($suggestions)

  return (
    <Autocomplete
      id='city'
      label='Search for a city'
      name='city'
      value={searchQuery}
      suggestions={suggestions}
      onChange={$searchInputValue}
    />
  )
}

// examples/weather/svelte-nano_kit-di/src/components/CityInput.svelte
<script lang="ts">
  import { inject } from '@nano_kit/svelte'
  import {
    LocationSearch$,
    CitySuggestions$
  } from '../stores/location.js'
  import Autocomplete from './Autocomplete.svelte'

  const { $searchInputValue: searchInputValue } = inject(LocationSearch$)
  const { $suggestions: suggestions } = inject(CitySuggestions$)
</script>

<Autocomplete
  id="city"
  label="Search for a city"
  name="city"
  value={$searchInputValue}
  suggestions={$suggestions}
  onChange={(value) => $searchInputValue = value}
/>
