// examples/weather/react-tanstack/src/App.tsx
import { WeatherProvider } from './stores/context.jsx'
import { CityInput } from './components/CityInput.jsx'
import { Weather } from './components/Weather.jsx'
import { Forecast } from './components/Forecast.jsx'

export function App() {
  return (
    <WeatherProvider>
      <main className='app'>
        <header>
          <h1 className='app-title'>
            Weather App
          </h1>
        </header>
        <CityInput/>
        <Weather/>
        <Forecast/>
      </main>
    </WeatherProvider>
  )
}

// examples/weather/svelte-nanostores/src/App.svelte
<script lang="ts">
  import CityInput from './components/CityInput.svelte'
  import Weather from './components/Weather.svelte'
  import Forecast from './components/Forecast.svelte'
</script>

<main class="app">
  <header>
    <h1 class="app-title">Weather App</h1>
  </header>
  <CityInput/>
  <Weather/>
  <Forecast/>
</main>
