// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/pages/Locations.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import { title } from '@nano_kit/svelte-router'
  import { Locations$ as LocationsStore$ } from '../../stores/locations.js'

  export function Head$() {
    return [
      title('Locations | Rick and Morty Wiki')
    ]
  }

  export function Stores$() {
    const { $locations: locations } = inject(LocationsStore$)

    return [locations]
  }
</script>

<script lang="ts">
  import { getInject } from '@nano_kit/svelte'
  import { Locations$ } from '../../stores/locations.js'
  import { Params$ } from '../../stores/router.js'
  import LocationGrid from '../blocks/LocationGrid.svelte'
  import Pagination from '../components/Pagination.svelte'
  import Spinner from '../components/Spinner.svelte'

  const {
    $locations: locations,
    $locationsError: locationsError,
    $locationsLoading: locationsLoading
  } = getInject(Locations$)
  const { $locationsPage: locationsPage } = getInject(Params$)
</script>

<section class="locations-container">
  {#if $locationsError}
    <div class="locations-error">
      <h2>Error loading locations</h2>
      <p>{$locationsError}</p>
    </div>
  {:else if $locationsLoading || !$locations}
    <Spinner>Loading locations...</Spinner>
  {:else}
    <LocationGrid locations={$locations.items} />
    <Pagination
      current={$locationsPage}
      total={$locations.totalPages}
      label="Location pages navigation"
    />
  {/if}
</section>

// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/Locations/Locations.tsx
/* DISCLAIMER! VIBECODED! */
import {
  useSignal,
  useInject
} from '@nano_kit/react'
import { inject } from '@nano_kit/store'
import { title } from '@nano_kit/router'
import { Params$ } from '#src/stores/router'
import { Locations$ } from '#src/stores/locations'
import { LocationsGrid } from '#src/ui/blocks/LocationsGrid'
import { Pagination } from '#src/ui/components/Pagination'
import { Spinner } from '#src/ui/components/Spinner'
import styles from './Locations.module.css'

export function Head$() {
  return [
    title('Rick and Morty Wiki | Locations')
  ]
}

export function Stores$() {
  const { $locations } = inject(Locations$)

  return [$locations]
}

function formatUrl(page: number) {
  return `?page=${page}`
}

function formatPageLabel(page: number) {
  return `Go to page ${page}`
}

export default function Locations() {
  const { $locationsPage } = useInject(Params$)
  const {
    $locations,
    $locationsError,
    $locationsLoading
  } = useInject(Locations$)
  const locationsPage = useSignal($locations)
  const currentPage = useSignal($locationsPage)
  const error = useSignal($locationsError)
  const loading = useSignal($locationsLoading)

  if (error) {
    return (
      <section className={styles.container}>
        <div className={styles.error}>
          <h2>Error loading locations</h2>
          <p>{error}</p>
        </div>
      </section>
    )
  }

  if (loading || !locationsPage) {
    return (
      <section className={styles.container}>
        <Spinner>Loading locations...</Spinner>
      </section>
    )
  }

  const {
    items: locations,
    totalPages
  } = locationsPage

  return (
    <section className={styles.container}>
      <LocationsGrid locations={locations} />

      {totalPages > 1 && (
        <Pagination
          current={currentPage}
          total={totalPages}
          formatUrl={formatUrl}
          previousLabel='Previous'
          nextLabel='Next'
          formatPageLabel={formatPageLabel}
          label='Location pages navigation'
        />
      )}
    </section>
  )
}
