// examples/event-board/react-nano_kit-ssr/src/ui/pages/Layout.tsx
import {
  Link,
  Outlet,
  meta,
  title,
  useLinkComponentAriaCurrent,
  useLinkComponentPreload,
  useSyncHead
} from '@nano_kit/react-router'

export function Head$() {
  return [
    title('Event Board'),
    meta({
      charSet: 'utf-8'
    }),
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    })
  ]
}

export default function Layout() {
  useSyncHead()
  useLinkComponentPreload(true)
  useLinkComponentAriaCurrent()

  return (
    <div className='app'>
      <header className='header'>
        <div className='container header__inner'>
          <Link to='home' className='brand'>
            Event Board
          </Link>

          <nav className='nav'>
            <Link to='home'>Events</Link>
            <Link to='newEvent'>New event</Link>
          </nav>
        </div>
      </header>

      <main className='container main'>
        <Outlet />
      </main>
    </div>
  )
}

// examples/event-board/svelte-nano_kit-ssr/src/ui/pages/Layout.svelte
<script module lang="ts">
  import {
    meta,
    title
  } from '@nano_kit/svelte-router'

  export function Head$() {
    return [
      title('Event Board'),
      meta({
        charSet: 'utf-8'
      }),
      meta({
        name: 'viewport',
        content: 'width=device-width, initial-scale=1'
      })
    ]
  }
</script>

<script lang="ts">
  import {
    enableLinkComponentAriaCurrent,
    enableLinkComponentPreload,
    Link,
    Outlet,
    syncHeadEffect
  } from '@nano_kit/svelte-router'

  syncHeadEffect()
  enableLinkComponentPreload(true)
  enableLinkComponentAriaCurrent()
</script>

<div class="app">
  <header class="header">
    <div class="container header__inner">
      <Link to="home" class="brand">Event Board</Link>

      <nav class="nav">
        <Link to="home">Events</Link>
        <Link to="newEvent">New event</Link>
      </nav>
    </div>
  </header>

  <main class="container main">
    <Outlet />
  </main>
</div>
