// examples/rick-and-morty/svelte-nano_kit/src/ui/pages/MainLayout.svelte
<script module lang="ts">
  import {
    meta,
    title
  } from '@nano_kit/svelte-router'

  export function Head$() {
    return [
      title('Rick and Morty Wiki'),
      meta({
        charSet: 'utf-8'
      }),
      meta({
        name: 'viewport',
        content: 'width=device-width, initial-scale=1'
      })
    ]
  }
</script>

<script lang="ts">
  import { Outlet } from '@nano_kit/svelte-router'
  import { Link } from '../components/Link.js'
</script>

<div class="main-layout-app">
  <header class="main-layout-header">
    <div class="main-layout-container">
      <h1 class="main-layout-title">
        <span class="main-layout-logo">🛸</span>
        Rick and Morty
      </h1>

      <nav class="main-layout-nav">
        <Link to="characters" class="main-layout-nav-link">Characters</Link>
        <Link to="locations" class="main-layout-nav-link">Locations</Link>
        <Link to="episodes" class="main-layout-nav-link">Episodes</Link>
      </nav>
    </div>
  </header>

  <main class="main-layout-main">
    <Outlet />
  </main>
</div>

// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/MainLayout/MainLayout.tsx
import {
  Link,
  Outlet,
  useSyncHead,
  useLinkComponentPreload,
  useLinkComponentAriaCurrent,
  meta,
  title
} from '@nano_kit/react-router'
import styles from './MainLayout.module.css'

export function Head$() {
  return [
    title('Rick and Morty Wiki'),
    meta({
      charSet: 'utf-8'
    }),
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    })
  ]
}

export default function MainLayout() {
  useSyncHead()
  useLinkComponentPreload(true)
  useLinkComponentAriaCurrent()

  return (
    <div className={styles.app}>
      <header className={styles.header}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            <span className={styles.logo}>🛸</span>
            Rick and Morty
          </h1>

          <nav className={styles.nav}>
            <Link to='characters' className={styles.navLink}>
              Characters
            </Link>
            <Link to='locations' className={styles.navLink}>
              Locations
            </Link>
            <Link to='episodes' className={styles.navLink}>
              Episodes
            </Link>
          </nav>
        </div>
      </header>

      <main className={styles.main}>
        <Outlet />
      </main>
    </div>
  )
}
