// examples/weather/svelte-nano_kit/src/components/CityInput.svelte
<script lang="ts">
  import {
    $locationSearchInputValue as locationSearchInputValue,
    $citySuggestions as citySuggestions
  } from '../stores/location.js'
  import Autocomplete from './Autocomplete.svelte'
</script>

<Autocomplete
  id="city"
  label="Search for a city"
  name="city"
  value={$locationSearchInputValue}
  suggestions={$citySuggestions}
  onChange={(value) => $locationSearchInputValue = value}
/>

// examples/weather/react-reatom/src/components/CityInput.tsx
import { useAtom } from '@reatom/react'
import {
  $locationSearchQuery,
  $citySuggestions
} from '../stores/location.js'
import { Autocomplete } from './Autocomplete.jsx'

export function CityInput() {
  const [locationSearchQuery, setLocationSearchQuery] = useAtom($locationSearchQuery)
  const [citySuggestions] = useAtom($citySuggestions)

  return (
    <Autocomplete
      id='city'
      label='Search for a city'
      name='city'
      value={locationSearchQuery}
      suggestions={citySuggestions}
      onChange={setLocationSearchQuery}
    />
  )
}
