// examples/session/react-nano_kit-ssr/src/ui/pages/Home.tsx
import {
  type FormEvent,
  useState
} from 'react'
import {
  useInject,
  useSignal
} from '@nano_kit/react'
import {
  meta,
  title,
  usePaths
} from '@nano_kit/react-router'
import { Session$ } from '#src/stores/session'

export function Head$() {
  return [
    title('Session Cookies | Nano Kit SSR'),
    meta({
      name: 'description',
      content: 'Cookie-backed session demo rendered with Nano Kit SSR.'
    })
  ]
}

export default function Home() {
  const paths = usePaths()
  const {
    $username,
    login
  } = useInject(Session$)
  const username = useSignal($username)
  const [input, setInput] = useState('')
  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    login(input)
    setInput('')
  }

  return (
    <section className='session'>
      <p className='eyebrow'>Cookie SSR demo</p>
      <h1>Session state without hydration mismatch</h1>
      <p className='intro'>
        The server reads the incoming cookie before rendering. The client hydrates the same session value.
      </p>

      {username
        ? (
          <div className='panel' aria-live='polite'>
            <p className='label'>Active session</p>
            <strong>{username}</strong>
            <a className='button' href={paths.logout}>
              Logout
            </a>
          </div>
        )
        : (
          <form className='panel form' onSubmit={onSubmit}>
            <label htmlFor='username'>
              Username
            </label>
            <input
              id='username'
              name='username'
              value={input}
              onChange={event => setInput(event.currentTarget.value)}
              autoComplete='username'
              required
            />
            <button type='submit'>
              Start session
            </button>
          </form>
        )}
    </section>
  )
}

// examples/session/svelte-kit-nano_kit-ssr/src/ui/pages/Home.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import { Session$ } from '../../stores/session.js'

  export function Stores$() {
    const { $username: username } = inject(Session$)

    return [username]
  }
</script>

<script lang="ts">
  import { getInject } from '@nano_kit/svelte-kit'

  const {
    $username: username,
    login
  } = getInject(Session$)
  let input = $state('')

  function onSubmit(event: SubmitEvent) {
    event.preventDefault()

    login(input)
    input = ''
  }
</script>

<svelte:head>
  <title>Session Cookies | Nano Kit SSR</title>
  <meta
    name="description"
    content="Cookie-backed session demo rendered with Nano Kit SSR."
  />
</svelte:head>

<section class="session">
  <p class="eyebrow">Cookie SSR demo</p>
  <h1>Session state without hydration mismatch</h1>
  <p class="intro">
    The server reads the incoming cookie before rendering. The client hydrates the same session value.
  </p>

  {#if $username}
    <div class="panel" aria-live="polite">
      <p class="label">Active session</p>
      <strong>{$username}</strong>
      <a class="button" href="/logout" data-sveltekit-reload>
        Logout
      </a>
    </div>
  {:else}
    <form class="panel form" onsubmit={onSubmit}>
      <label for="username">
        Username
      </label>
      <input
        id="username"
        name="username"
        bind:value={input}
        autocomplete="username"
        required
      />
      <button type="submit">
        Start session
      </button>
    </form>
  {/if}
</section>
