// examples/weather/svelte-nano_kit-di/src/components/Forecast.svelte
<script lang="ts">
  import { getInject } from '@nano_kit/svelte'
  import { WeatherForecast$ } from '../stores/weather.js'
  import ForecastWeather from './ForecastWeather.svelte'

  const { $forecast: forecast } = getInject(WeatherForecast$)
  let mode: 'hourly' | 'daily' = $state('hourly')
  let forecastToShow = $derived($forecast.filter(
    (weather, index) => (
      mode === 'hourly' && weather.period === 'hourly' && index < 24
        || mode === 'daily' && weather.period === 'daily'
    )
  ))
</script>

{#if forecastToShow?.length}
  <section>
    <header class="forecast-header">
      <h2 class="forecast-title">Forecast</h2>
      <select
        class="forecast-mode"
        bind:value={mode}
      >
        <option value="hourly">Hourly</option>
        <option value="daily">Daily</option>
      </select>
    </header>
    <ul class="forecast-list">
      {#each forecastToShow as weather}
        <ForecastWeather {weather} {mode} />
      {/each}
    </ul>
  </section>
{/if}

// examples/weather/react-nano_kit/src/components/Forecast.tsx
/* oxlint-disable eslint/no-magic-numbers */
import {
  useState,
  useMemo,
  useCallback
} from 'react'
import { useSignal } from '@nano_kit/react'
import { $weatherForecast } from '../stores/weather.js'
import { ForecastWeather } from './ForecastWeather.jsx'

export function Forecast() {
  const weatherForecast = useSignal($weatherForecast)
  const [mode, setMode] = useState('hourly')
  const forecastToShow = useMemo(
    () => weatherForecast.filter(
      (weather, index) => mode === 'hourly' && weather.period === 'hourly' && index < 24
        || mode === 'daily' && weather.period === 'daily'
    ),
    [weatherForecast, mode]
  )
  const handleModeChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => setMode(e.target.value),
    []
  )

  if (weatherForecast.length === 0) {
    return null
  }

  return (
    <section>
      <header className='forecast-header'>
        <h2 className='forecast-title'>
          Forecast
        </h2>
        <select
          className='forecast-mode'
          value={mode}
          onChange={handleModeChange}
        >
          <option value='hourly'>
            Hourly
          </option>
          <option value='daily'>
            Daily
          </option>
        </select>
      </header>
      <ul className='forecast-list'>
        {forecastToShow.map(weather => (
          <ForecastWeather
            key={weather.dateText}
            weather={weather}
            mode={mode}
          />
        ))}
      </ul>
    </section>
  )
}
