// examples/weather/svelte-nano_kit/src/components/Weather.svelte
<script lang="ts">
  import {
    $currentLocation as currentLocation
  } from '../stores/location.js'
  import {
    $currentWeather as currentWeather
  } from '../stores/weather.js'
</script>

{#if $currentWeather}
  <div
    class="weather"
    data-city={$currentLocation?.name}
  >
    <h3 class="weather-temp">
      {$currentWeather.tempText}
    </h3>
    <img
      class="weather-icon"
      src={$currentWeather.icon}
      alt={$currentWeather.description}
    />
    <p class="weather-feels-like">
      Feels like {$currentWeather.feelsLikeText}
    </p>
    <p class="weather-description">
      {$currentWeather.description}
      <br>
      Humidity: {$currentWeather.humidity}%
    </p>
  </div>
{/if}

// examples/weather/react-nanostores/src/components/Weather.tsx
import { useStore } from '@nanostores/react'
import { $currentLocation } from '../stores/location.js'
import { $currentWeather } from '../stores/weather.js'

export function Weather() {
  const currentWeather = useStore($currentWeather)
  const city = useStore($currentLocation)

  if (!currentWeather) {
    return null
  }

  return (
    <div
      className='weather'
      data-city={city?.name}
    >
      <h3 className='weather-temp'>
        {currentWeather.tempText}
      </h3>
      <img
        className='weather-icon'
        src={currentWeather.icon}
        alt={currentWeather.description}
      />
      <p
        className='weather-feels-like'
      >
        Feels like
        {' '}
        {currentWeather.feelsLikeText}
      </p>
      <p className='weather-description'>
        {currentWeather.description}
        <br/>
        Humidity:
        {' '}
        {currentWeather.humidity}
        %
      </p>
    </div>
  )
}
