// examples/weather/react-reatom/src/components/ForecastWeather.tsx
import { useMemo } from 'react'
import type { Weather } from '../services/types.js'

export interface Props {
  weather: Weather
  mode: string
}

export function ForecastWeather({
  weather,
  mode
}: Props) {
  const weatherTime = useMemo(() => {
    const { date } = weather

    if (!date) {
      return ''
    }

    if (mode === 'hourly') {
      return date.toLocaleTimeString(undefined, {
        hour: 'numeric',
        minute: '2-digit'
      })
    }

    return date.toLocaleDateString(undefined, {
      day: 'numeric',
      month: 'short'
    })
  }, [weather, mode])

  return (
    <div className='forecast-item'>
      <time
        className='forecast-time'
        dateTime={weather.dateText}
      >
        {weatherTime}
      </time>
      <img
        className='forecast-icon'
        src={weather.icon}
        alt={weather.description}
      />
      <h3 className='forecast-temp'>
        {weather.tempText}
      </h3>
      <p className='forecast-description'>
        {weather.description}
      </p>
    </div>
  )
}

// examples/weather/svelte-nanostores/src/components/ForecastWeather.svelte
<script lang="ts">
  import type { Weather } from '../services/types.js'

  interface Props {
    weather: Readonly<Weather>
    mode: 'hourly' | 'daily'
  }

  let { weather, mode }: Props = $props()
</script>

<div class="forecast-item">
  <time class="forecast-time" datetime={weather.dateText}>
    {#if mode === 'hourly'}
      {weather.date.toLocaleTimeString(undefined, {
        hour: 'numeric',
        minute: '2-digit'
      })}
    {:else}
      {weather.date.toLocaleDateString(undefined, {
        day: 'numeric',
        month: 'short',
      })}
    {/if}
  </time>
  <img
    class="forecast-icon"
    src={weather.icon}
    alt={weather.description}
  />
  <h3 class="forecast-temp">
    {weather.tempText}
  </h3>
  <p class="forecast-description">
    {weather.description}
  </p>
</div>
