// examples/weather/react-tanstack/src/components/ForecastWeather.tsx
import type { Weather } from '../services/types.js'

interface Props {
  weather: Weather
  mode: string
}

export function ForecastWeather({ weather, mode }: Props) {
  return (
    <div className='forecast-item'>
      <time
        className='forecast-time'
        dateTime={weather.dateText}
      >
        {mode === 'hourly'
          ? weather.date.toLocaleTimeString(undefined, {
            hour: 'numeric',
            minute: '2-digit'
          })
          : weather.date.toLocaleDateString(undefined, {
            day: 'numeric',
            month: 'short'
          })}
      </time>
      <img
        className='forecast-icon'
        src={weather.icon}
        alt={weather.description}
      />
      <h3
        className='forecast-temp'
      >
        {weather.tempText}
      </h3>
      <p className='forecast-description'>
        {weather.description}
      </p>
    </div>
  )
}

// examples/weather/svelte-nanostores/src/components/ForecastWeather.svelte
<script lang="ts">
  import type { Weather } from '../services/types.js'

  interface Props {
    weather: Readonly<Weather>
    mode: 'hourly' | 'daily'
  }

  let { weather, mode }: Props = $props()
</script>

<div class="forecast-item">
  <time class="forecast-time" datetime={weather.dateText}>
    {#if mode === 'hourly'}
      {weather.date.toLocaleTimeString(undefined, {
        hour: 'numeric',
        minute: '2-digit'
      })}
    {:else}
      {weather.date.toLocaleDateString(undefined, {
        day: 'numeric',
        month: 'short',
      })}
    {/if}
  </time>
  <img
    class="forecast-icon"
    src={weather.icon}
    alt={weather.description}
  />
  <h3 class="forecast-temp">
    {weather.tempText}
  </h3>
  <p class="forecast-description">
    {weather.description}
  </p>
</div>
