// examples/rick-and-morty/react-nano_kit/src/ui/pages/Episodes/Episodes.tsx
/* DISCLAIMER! VIBECODED! */
import { useSignal } from '@nano_kit/react'
import { $episodesPage } from '#src/stores/router'
import {
  $episodes,
  $episodesError,
  $episodesLoading
} from '#src/stores/episodes'
import { EpisodesGrid } from '#src/ui/blocks/EpisodesGrid'
import { Pagination } from '#src/ui/components/Pagination'
import { Spinner } from '#src/ui/components/Spinner'
import styles from './Episodes.module.css'

function formatUrl(page: number) {
  return `?page=${page}`
}

function formatPageLabel(page: number) {
  return `Go to page ${page}`
}

export function Episodes() {
  const episodesPage = useSignal($episodes)
  const error = useSignal($episodesError)
  const loading = useSignal($episodesLoading)
  const currentPage = useSignal($episodesPage)

  if (loading || !episodesPage) {
    return (
      <section className={styles.container}>
        <Spinner>Loading episodes...</Spinner>
      </section>
    )
  }

  if (error) {
    return (
      <section className={styles.container}>
        <div className={styles.error}>
          <h2>Error loading episodes</h2>
          <p>{error}</p>
        </div>
      </section>
    )
  }

  const {
    items: episodes,
    totalPages
  } = episodesPage

  return (
    <section className={styles.container}>
      <EpisodesGrid episodes={episodes} />

      {totalPages > 1 && (
        <Pagination
          current={currentPage}
          total={totalPages}
          formatUrl={formatUrl}
          previousLabel='Previous'
          nextLabel='Next'
          formatPageLabel={formatPageLabel}
          label='Episode pages navigation'
        />
      )}
    </section>
  )
}

// examples/rick-and-morty/svelte-kit-nano_kit-ssr/src/ui/pages/Episodes.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import { Episodes$ } from '../../stores/episodes.js'

  export function Stores$() {
    const { $episodes: episodes } = inject(Episodes$)

    return [episodes]
  }
</script>

<script lang="ts">
  import { getInject } from '@nano_kit/svelte'
  import { Params$ } from '../../stores/router.js'
  import EpisodeGrid from '../blocks/EpisodeGrid.svelte'
  import Pagination from '../components/Pagination.svelte'
  import Spinner from '../components/Spinner.svelte'

  const {
    $episodes: episodes,
    $episodesError: episodesError,
    $episodesLoading: episodesLoading
  } = getInject(Episodes$)
  const { $episodesPage: episodesPage } = getInject(Params$)
</script>

<section class="episodes-container">
  {#if $episodesError}
    <div class="episodes-error">
      <h2>Error loading episodes</h2>
      <p>{$episodesError}</p>
    </div>
  {:else if $episodesLoading || !$episodes}
    <Spinner>Loading episodes...</Spinner>
  {:else}
    <EpisodeGrid episodes={$episodes.items} />
    <Pagination
      current={$episodesPage}
      total={$episodes.totalPages}
      label="Episode pages navigation"
    />
  {/if}
</section>
