// examples/rick-and-morty/next-app-nano_kit-ssr/src/ui/pages/Locations.tsx
/* DISCLAIMER! VIBECODED! */
'use client'
import {
  useSignal,
  useInject
} from '@nano_kit/react'
import { Params$ } from '@/stores/router'
import { Locations$ } from '@/stores/locations'
import { LocationsGrid } from '@/ui/blocks/LocationsGrid'
import { Pagination } from '@/ui/components/Pagination'
import { Spinner } from '@/ui/components/Spinner'

function formatUrl(page: number) {
  return `?page=${page}`
}

function formatPageLabel(page: number) {
  return `Go to page ${page}`
}

export default function Locations() {
  const { $locationsPage } = useInject(Params$)
  const {
    $locations,
    $locationsError,
    $locationsLoading
  } = useInject(Locations$)
  const locationsPage = useSignal($locations)
  const currentPage = useSignal($locationsPage)
  const error = useSignal($locationsError)
  const loading = useSignal($locationsLoading)

  if (error) {
    return (
      <section className='locations-container'>
        <div className='locations-error'>
          <h2>Error loading locations</h2>
          <p>{error}</p>
        </div>
      </section>
    )
  }

  if (loading || !locationsPage) {
    return (
      <section className='locations-container'>
        <Spinner>Loading locations...</Spinner>
      </section>
    )
  }

  const {
    items: locations,
    totalPages
  } = locationsPage

  return (
    <section className='locations-container'>
      <LocationsGrid locations={locations} />

      {totalPages > 1 && (
        <Pagination
          current={currentPage}
          total={totalPages}
          formatUrl={formatUrl}
          previousLabel='Previous'
          nextLabel='Next'
          formatPageLabel={formatPageLabel}
          label='Location pages navigation'
        />
      )}
    </section>
  )
}

// examples/rick-and-morty/svelte-kit-nano_kit-ssr/src/ui/pages/Locations.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import { Locations$ } from '../../stores/locations.js'

  export function Stores$() {
    const { $locations: locations } = inject(Locations$)

    return [locations]
  }
</script>

<script lang="ts">
  import { getInject } from '@nano_kit/svelte'
  import { Params$ } from '../../stores/router.js'
  import LocationGrid from '../blocks/LocationGrid.svelte'
  import Pagination from '../components/Pagination.svelte'
  import Spinner from '../components/Spinner.svelte'

  const {
    $locations: locations,
    $locationsError: locationsError,
    $locationsLoading: locationsLoading
  } = getInject(Locations$)
  const { $locationsPage: locationsPage } = getInject(Params$)
</script>

<section class="locations-container">
  {#if $locationsError}
    <div class="locations-error">
      <h2>Error loading locations</h2>
      <p>{$locationsError}</p>
    </div>
  {:else if $locationsLoading || !$locations}
    <Spinner>Loading locations...</Spinner>
  {:else}
    <LocationGrid locations={$locations.items} />
    <Pagination
      current={$locationsPage}
      total={$locations.totalPages}
      label="Location pages navigation"
    />
  {/if}
</section>
