// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/Location.tsx
/* DISCLAIMER! VIBECODED! */
import {
  useSignal,
  useInject
} from '@nano_kit/react'
import {
  computed,
  inject
} from '@nano_kit/store'
import { title } from '@nano_kit/router'
import { Location$ } from '#src/stores/locations'
import { Residents$ } from '#src/stores/characters'
import { LocationDetail } from '#src/ui/blocks/LocationDetail'
import { CharactersGrid } from '#src/ui/blocks/CharactersGrid'
import { Spinner } from '#src/ui/components/Spinner'

export function Head$() {
  const { $location } = inject(Location$)

  return [
    title(computed(() => `${$location()?.name || 'Location'} | Rick and Morty Wiki`))
  ]
}

export function Stores$() {
  const { $location } = inject(Location$)
  const { $residents } = inject(Residents$)

  return [$location, $residents]
}

export default function Location() {
  const {
    $locationError,
    $locationLoading
  } = useInject(Location$)
  const { $residents } = useInject(Residents$)
  const residents = useSignal($residents)
  const error = useSignal($locationError)
  const loading = useSignal($locationLoading)

  if (error) {
    return (
      <div className='location-error'>
        <h2>Error loading location</h2>
        <p>{error}</p>
      </div>
    )
  }

  if (loading || !residents) {
    return <Spinner>Loading location...</Spinner>
  }

  return (
    <section className='location-container'>
      <LocationDetail />

      <div className='location-residents-section'>
        <h2 id='residents' className='location-residents-title'>
          <a href='#residents'>Residents ({residents.length})</a>
        </h2>
        <CharactersGrid characters={residents} />
      </div>
    </section>
  )
}

// examples/rick-and-morty/svelte-kit-nano_kit-ssr/src/ui/pages/Location.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import { Residents$ } from '../../stores/characters.js'
  import { Location$ } from '../../stores/locations.js'

  export function Stores$() {
    const { $location: location } = inject(Location$)
    const { $residents: residents } = inject(Residents$)

    return [location, residents]
  }
</script>

<script lang="ts">
  import { getInject } from '@nano_kit/svelte'
  import CharacterGrid from '../blocks/CharacterGrid.svelte'
  import Spinner from '../components/Spinner.svelte'

  const {
    $residents: residents,
    $residentsError: residentsError,
    $residentsLoading: residentsLoading
  } = getInject(Residents$)
  const {
    $location: location,
    $locationError: locationError
  } = getInject(Location$)
</script>

<svelte:head>
  <title>{$location?.name || 'Location'} | Rick and Morty Wiki</title>
</svelte:head>

{#if $locationError || $residentsError}
  <div class="location-error">
    <h2>Error loading location</h2>
    <p>{$locationError || $residentsError}</p>
  </div>
{:else if $residentsLoading || !$location || !$residents}
  <Spinner>Loading location...</Spinner>
{:else}
  <section class="location-container">
    <div class="location-detail-header">
      <div class="location-detail-info">
        <h1 class="location-detail-name">{$location.name}</h1>
        <p class="location-detail-type">
          <span class="location-detail-label">Type:</span>
          <span class="location-detail-value">{$location.type}</span>
        </p>
        <p class="location-detail-dimension">
          <span class="location-detail-label">Dimension:</span>
          <span class="location-detail-value">{$location.dimension}</span>
        </p>
      </div>
    </div>

    <div class="location-detail-details">
      <article class="location-detail-section">
        <h2>Residents</h2>
        <p>{$location.residents.length} residents</p>
      </article>
    </div>

    <section class="location-residents-section">
      <h2 id="residents" class="location-residents-title">
        <a href="#residents">Residents ({$residents.length})</a>
      </h2>
      <CharacterGrid characters={$residents} />
    </section>
  </section>
{/if}
