// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/blocks/LocationCard.svelte
<script lang="ts">
  import type { Location } from '#src/services/api'
  import { Link } from '@nano_kit/svelte-router'

  interface Props {
    location: Location
  }

  const { location }: Props = $props()
</script>

<article class="location-card-card">
  <Link to="location" params={{ id: location.id }} class="location-card-link">
    <div class="location-card-content">
      <h2 class="location-card-name">{location.name}</h2>
      <dl class="location-card-info">
        <div class="location-card-row">
          <dt class="location-card-label">Type</dt>
          <dd class="location-card-value">{location.type}</dd>
        </div>
        <div class="location-card-row">
          <dt class="location-card-label">Dimension</dt>
          <dd class="location-card-value">{location.dimension}</dd>
        </div>
        <div class="location-card-row">
          <dt class="location-card-label">Residents</dt>
          <dd class="location-card-value">{location.residents.length}</dd>
        </div>
      </dl>
    </div>
  </Link>
</article>

// examples/rick-and-morty/react-nano_kit-ssr/src/ui/blocks/LocationCard.tsx
/* DISCLAIMER! VIBECODED! */
import { Link } from '@nano_kit/react-router'
import type { Location } from '#src/services/api'

export interface LocationCardProps {
  location: Location
}

export function LocationCard({ location }: LocationCardProps) {
  return (
    <article className='location-card-card'>
      <Link
        to='location'
        params={{
          id: location.id
        }}
        className='location-card-link'
      >
        <div className='location-card-content'>
          <h2 className='location-card-name'>{location.name}</h2>

          <div className='location-card-info'>
            <div className='location-card-row'>
              <span className='location-card-label'>Type:</span>
              <span className='location-card-value'>{location.type}</span>
            </div>

            <div className='location-card-row'>
              <span className='location-card-label'>Dimension:</span>
              <span className='location-card-value'>{location.dimension}</span>
            </div>

            <div className='location-card-row'>
              <span className='location-card-label'>Residents:</span>
              <span className='location-card-value'>{location.residents.length}</span>
            </div>
          </div>
        </div>
      </Link>
    </article>
  )
}
