// examples/rick-and-morty/react-nano_kit-ssr/src/ui/blocks/LocationCard/LocationCard.tsx
/* DISCLAIMER! VIBECODED! */
import { Link } from '@nano_kit/react-router'
import { type Location } from '#src/services/api'
import styles from './LocationCard.module.css'

export interface LocationCardProps {
  location: Location
}

export function LocationCard({ location }: LocationCardProps) {
  return (
    <article className={styles.card}>
      <Link
        to='location'
        params={{
          id: location.id
        }}
        className={styles.link}
      >
        <div className={styles.content}>
          <h2 className={styles.name}>{location.name}</h2>

          <div className={styles.info}>
            <div className={styles.row}>
              <span className={styles.label}>Type:</span>
              <span className={styles.value}>{location.type}</span>
            </div>

            <div className={styles.row}>
              <span className={styles.label}>Dimension:</span>
              <span className={styles.value}>{location.dimension}</span>
            </div>

            <div className={styles.row}>
              <span className={styles.label}>Residents:</span>
              <span className={styles.value}>{location.residents.length}</span>
            </div>
          </div>
        </div>
      </Link>
    </article>
  )
}

// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/blocks/LocationCard.svelte
<script lang="ts">
  import type { Location } from '#src/services/api'
  import { Link } from '@nano_kit/svelte-router'

  interface Props {
    location: Location
  }

  const { location }: Props = $props()
</script>

<article class="location-card-card">
  <Link to="location" params={{ id: location.id }} class="location-card-link">
    <div class="location-card-content">
      <h2 class="location-card-name">{location.name}</h2>
      <dl class="location-card-info">
        <div class="location-card-row">
          <dt class="location-card-label">Type</dt>
          <dd class="location-card-value">{location.type}</dd>
        </div>
        <div class="location-card-row">
          <dt class="location-card-label">Dimension</dt>
          <dd class="location-card-value">{location.dimension}</dd>
        </div>
        <div class="location-card-row">
          <dt class="location-card-label">Residents</dt>
          <dd class="location-card-value">{location.residents.length}</dd>
        </div>
      </dl>
    </div>
  </Link>
</article>
