// examples/rick-and-morty/react-nano_kit-ssr/src/ui/blocks/EpisodeCard.tsx
/* DISCLAIMER! VIBECODED! */
import { Link } from '@nano_kit/react-router'
import type { Episode } from '#src/services/api'

export interface EpisodeCardProps {
  episode: Episode
}

export function EpisodeCard({ episode }: EpisodeCardProps) {
  return (
    <article className='episode-card-card'>
      <Link
        to='episode'
        params={{
          id: episode.id
        }}
        className='episode-card-link'
      >
        <div className='episode-card-content'>
          <h2 className='episode-card-name'>{episode.name}</h2>

          <div className='episode-card-info'>
            <div className='episode-card-row'>
              <span className='episode-card-label'>Episode:</span>
              <span className='episode-card-value'>{episode.episode}</span>
            </div>

            <div className='episode-card-row'>
              <span className='episode-card-label'>Air Date:</span>
              <span className='episode-card-value'>{episode.air_date}</span>
            </div>

            <div className='episode-card-row'>
              <span className='episode-card-label'>Characters:</span>
              <span className='episode-card-value'>{episode.characters.length}</span>
            </div>
          </div>
        </div>
      </Link>
    </article>
  )
}

// examples/rick-and-morty/svelte-kit-nano_kit-ssr/src/ui/blocks/EpisodeCard.svelte
<script lang="ts">
  import { Link } from '@nano_kit/svelte-kit'
  import type { Episode } from '#src/services/api'

  interface Props {
    episode: Episode
  }

  const { episode }: Props = $props()
</script>

<article class="episode-card-card">
  <Link to="episode" params={{ id: episode.id }} class="episode-card-link">
    <div class="episode-card-content">
      <h2 class="episode-card-name">{episode.name}</h2>
      <dl class="episode-card-info">
        <div class="episode-card-row">
          <dt class="episode-card-label">Episode</dt>
          <dd class="episode-card-value">{episode.episode}</dd>
        </div>
        <div class="episode-card-row">
          <dt class="episode-card-label">Air date</dt>
          <dd class="episode-card-value">{episode.air_date}</dd>
        </div>
        <div class="episode-card-row">
          <dt class="episode-card-label">Characters</dt>
          <dd class="episode-card-value">{episode.characters.length}</dd>
        </div>
      </dl>
    </div>
  </Link>
</article>
