// examples/rick-and-morty/svelte-nano_kit/src/ui/pages/Episodes.svelte
<script module lang="ts">
  import { title } from '@nano_kit/svelte-router'

  export function Head$() {
    return [
      title('Episodes | Rick and Morty Wiki')
    ]
  }
</script>

<script lang="ts">
  import {
    $episodes as episodes,
    $episodesError as episodesError,
    $episodesLoading as episodesLoading
  } from '../../stores/episodes.js'
  import { $episodesPage as episodesPage } from '../../stores/router.js'
  import EpisodeGrid from '../blocks/EpisodeGrid.svelte'
  import Pagination from '../components/Pagination.svelte'
  import Spinner from '../components/Spinner.svelte'
</script>

<section class="episodes-container">
  {#if $episodesError}
    <div class="episodes-error">
      <h2>Error loading episodes</h2>
      <p>{$episodesError}</p>
    </div>
  {:else if $episodesLoading || !$episodes}
    <Spinner>Loading episodes...</Spinner>
  {:else}
    <EpisodeGrid episodes={$episodes.items} />
    <Pagination
      current={$episodesPage}
      total={$episodes.totalPages}
      label="Episode pages navigation"
    />
  {/if}
</section>

// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/Episodes.tsx
/* DISCLAIMER! VIBECODED! */
import {
  useSignal,
  useInject
} from '@nano_kit/react'
import { inject } from '@nano_kit/store'
import { title } from '@nano_kit/router'
import { Params$ } from '#src/stores/router'
import { Episodes$ } from '#src/stores/episodes'
import { EpisodesGrid } from '#src/ui/blocks/EpisodesGrid'
import { Pagination } from '#src/ui/components/Pagination'
import { Spinner } from '#src/ui/components/Spinner'

export function Head$() {
  return [
    title('Episodes | Rick and Morty Wiki')
  ]
}

export function Stores$() {
  const { $episodes } = inject(Episodes$)

  return [$episodes]
}

function formatUrl(page: number) {
  return `?page=${page}`
}

function formatPageLabel(page: number) {
  return `Go to page ${page}`
}

export default function Episodes() {
  const { $episodesPage } = useInject(Params$)
  const {
    $episodes,
    $episodesError,
    $episodesLoading
  } = useInject(Episodes$)
  const episodesPage = useSignal($episodes)
  const error = useSignal($episodesError)
  const loading = useSignal($episodesLoading)
  const currentPage = useSignal($episodesPage)

  if (error) {
    return (
      <section className='episodes-container'>
        <div className='episodes-error'>
          <h2>Error loading episodes</h2>
          <p>{error}</p>
        </div>
      </section>
    )
  }

  if (loading || !episodesPage) {
    return (
      <section className='episodes-container'>
        <Spinner>Loading episodes...</Spinner>
      </section>
    )
  }

  const {
    items: episodes,
    totalPages
  } = episodesPage

  return (
    <section className='episodes-container'>
      <EpisodesGrid episodes={episodes} />

      {totalPages > 1 && (
        <Pagination
          current={currentPage}
          total={totalPages}
          formatUrl={formatUrl}
          previousLabel='Previous'
          nextLabel='Next'
          formatPageLabel={formatPageLabel}
          label='Episode pages navigation'
        />
      )}
    </section>
  )
}
