// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/pages/Home.svelte
<script module lang="ts">
  import { inject } from '@nano_kit/store'
  import {
    Navigation$,
    Paths$
  } from '@nano_kit/svelte-router'

  export function Stores$() {
    const navigation = inject(Navigation$)
    const paths = inject(Paths$)

    navigation.replace(paths.characters, true)

    return []
  }
</script>

// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/Home.tsx
import { inject } from '@nano_kit/store'
import {
  Navigation$,
  Paths$
} from '@nano_kit/router'

export function Stores$() {
  const navigation = inject(Navigation$)
  const paths = inject(Paths$)

  navigation.replace(paths.characters, true)

  return []
}

export default function Home() {
  return <></>
}
