// examples/rick-and-morty/react-nano_kit/src/ui/blocks/EpisodeCard/EpisodeCard.tsx
/* DISCLAIMER! VIBECODED! */
import { type Episode } from '#src/services/api'
import { Link } from '#src/ui/components/Link'
import styles from './EpisodeCard.module.css'

export interface EpisodeCardProps {
  episode: Episode
}

export function EpisodeCard({ episode }: EpisodeCardProps) {
  return (
    <article className={styles.card}>
      <Link
        to='episode'
        params={{
          id: episode.id
        }}
        className={styles.link}
      >
        <div className={styles.content}>
          <h2 className={styles.name}>{episode.name}</h2>

          <div className={styles.info}>
            <div className={styles.row}>
              <span className={styles.label}>Episode:</span>
              <span className={styles.value}>{episode.episode}</span>
            </div>

            <div className={styles.row}>
              <span className={styles.label}>Air Date:</span>
              <span className={styles.value}>{episode.air_date}</span>
            </div>

            <div className={styles.row}>
              <span className={styles.label}>Characters:</span>
              <span className={styles.value}>{episode.characters.length}</span>
            </div>
          </div>
        </div>
      </Link>
    </article>
  )
}

// examples/rick-and-morty/svelte-nano_kit/src/ui/blocks/EpisodeCard.svelte
<script lang="ts">
  import type { Episode } from '#src/services/api'
  import { Link } from '../components/Link.js'

  interface Props {
    episode: Episode
  }

  const { episode }: Props = $props()
</script>

<article class="episode-card-card">
  <Link to="episode" params={{ id: episode.id }} class="episode-card-link">
    <div class="episode-card-content">
      <h2 class="episode-card-name">{episode.name}</h2>
      <dl class="episode-card-info">
        <div class="episode-card-row">
          <dt class="episode-card-label">Episode</dt>
          <dd class="episode-card-value">{episode.episode}</dd>
        </div>
        <div class="episode-card-row">
          <dt class="episode-card-label">Air date</dt>
          <dd class="episode-card-value">{episode.air_date}</dd>
        </div>
        <div class="episode-card-row">
          <dt class="episode-card-label">Characters</dt>
          <dd class="episode-card-value">{episode.characters.length}</dd>
        </div>
      </dl>
    </div>
  </Link>
</article>
