// examples/rick-and-morty/react-nano_kit-ssr/src/ui/pages/MainLayout.tsx
import {
  Link,
  Outlet,
  useSyncHead,
  useLinkComponentPreload,
  useLinkComponentAriaCurrent,
  meta,
  title
} from '@nano_kit/react-router'

export function Head$() {
  return [
    title('Rick and Morty Wiki'),
    meta({
      charSet: 'utf-8'
    }),
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    })
  ]
}

export default function MainLayout() {
  useSyncHead()
  useLinkComponentPreload(true)
  useLinkComponentAriaCurrent()

  return (
    <div className='main-layout-app'>
      <header className='main-layout-header'>
        <div className='main-layout-container'>
          <h1 className='main-layout-title'>
            <span className='main-layout-logo'>🛸</span>
            Rick and Morty
          </h1>

          <nav className='main-layout-nav'>
            <Link to='characters' className='main-layout-nav-link'>
              Characters
            </Link>
            <Link to='locations' className='main-layout-nav-link'>
              Locations
            </Link>
            <Link to='episodes' className='main-layout-nav-link'>
              Episodes
            </Link>
          </nav>
        </div>
      </header>

      <main className='main-layout-main'>
        <Outlet />
      </main>
    </div>
  )
}

// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/pages/MainLayout.svelte
<script module lang="ts">
  import {
    meta,
    title
  } from '@nano_kit/svelte-router'

  export function Head$() {
    return [
      title('Rick and Morty Wiki'),
      meta({
        charSet: 'utf-8'
      }),
      meta({
        name: 'viewport',
        content: 'width=device-width, initial-scale=1'
      })
    ]
  }
</script>

<script lang="ts">
  import {
    enableLinkComponentAriaCurrent,
    enableLinkComponentPreload,
    Link,
    Outlet,
    syncHeadEffect
  } from '@nano_kit/svelte-router'

  syncHeadEffect()
  enableLinkComponentPreload(true)
  enableLinkComponentAriaCurrent()
</script>

<div class="main-layout-app">
  <header class="main-layout-header">
    <div class="main-layout-container">
      <h1 class="main-layout-title">
        <span class="main-layout-logo">🛸</span>
        Rick and Morty
      </h1>

      <nav class="main-layout-nav">
        <Link to="characters" class="main-layout-nav-link">Characters</Link>
        <Link to="locations" class="main-layout-nav-link">Locations</Link>
        <Link to="episodes" class="main-layout-nav-link">Episodes</Link>
      </nav>
    </div>
  </header>

  <main class="main-layout-main">
    <Outlet />
  </main>
</div>
