// examples/rick-and-morty/svelte-nano_kit-ssr/src/ui/blocks/CharacterCard.svelte
<script lang="ts">
  import { Link } from '@nano_kit/svelte-router'
  import type { Character } from '#src/services/api'

  interface Props {
    character: Character
  }

  const { character }: Props = $props()
</script>

<article class="character-card-card">
  <Link
    to="character"
    params={{ id: character.id }}
    class="character-card-link"
  >
    <div class="character-card-image-wrapper">
      <img class="character-card-image" src={character.image} alt={character.name} loading="lazy" />
    </div>

    <div class="character-card-content">
      <h2 class="character-card-name">{character.name}</h2>

      <dl class="character-card-info">
        <div class="character-card-row">
          <dt class="character-card-label">Status</dt>
          <dd class={`character-card-status character-card-status--${character.status.toLowerCase()}`}>{character.status}</dd>
        </div>
        <div class="character-card-row">
          <dt class="character-card-label">Species</dt>
          <dd class="character-card-value">{character.species}</dd>
        </div>
        <div class="character-card-row">
          <dt class="character-card-label">Origin</dt>
          <dd class="character-card-value">{character.origin.name}</dd>
        </div>
        <div class="character-card-row">
          <dt class="character-card-label">Episodes</dt>
          <dd class="character-card-value">{character.episode.length}</dd>
        </div>
      </dl>
    </div>
  </Link>
</article>

// examples/rick-and-morty/next-app-nano_kit-ssr/src/ui/blocks/CharacterCard.tsx
/* DISCLAIMER! VIBECODED! */
'use client'
import clsx from 'clsx'
import { Link } from '@nano_kit/next-router'
import { type Character } from '@/services/api'

export interface CharacterCardProps {
  character: Character
}

export function CharacterCard({ character }: CharacterCardProps) {
  return (
    <article className='character-card-card'>
      <Link
        className='character-card-link'
        to='character'
        params={{
          id: character.id
        }}
      >
        <div className='character-card-image-wrapper'>
          <img
            src={character.image}
            alt={character.name}
            className='character-card-image'
            loading='lazy'
          />
        </div>

        <div className='character-card-content'>
          <h2 className='character-card-name'>{character.name}</h2>

          <div className='character-card-info'>
            <div className='character-card-row'>
              <span className='character-card-label'>Status:</span>
              <span className={clsx('character-card-status', `character-card-status--${character.status.toLowerCase()}`)}>
                {character.status}
              </span>
            </div>

            <div className='character-card-row'>
              <span className='character-card-label'>Species:</span>
              <span className='character-card-value'>{character.species}</span>
            </div>

            <div className='character-card-row'>
              <span className='character-card-label'>Gender:</span>
              <span className='character-card-value'>{character.gender}</span>
            </div>

            <div className='character-card-row'>
              <span className='character-card-label'>Origin:</span>
              <span className='character-card-value'>{character.origin.name}</span>
            </div>

            <div className='character-card-row'>
              <span className='character-card-label'>Location:</span>
              <span className='character-card-value'>{character.location.name}</span>
            </div>

            <div className='character-card-row'>
              <span className='character-card-label'>Episodes:</span>
              <span className='character-card-value'>{character.episode.length}</span>
            </div>
          </div>
        </div>
      </Link>
    </article>
  )
}
